### ISSUE TITLE
The source of the Dev dataset used in the MT-DNN model

### ISSUE THREAD

**Issue by Dsakula** [Aadil101/BigGreen-at-LCP-2021#3] opened 2022-09-27 14:01 UTC
Hi！Thank you very much for your update. I also have a question about the Dev dataset you used when training the MT-DNN model. In your paper, you only mentioned the use of text dataset and train dataset from the Complex1.0, not the source of the Dev dataset. I hope you can tell me the source of the Dev dataset. Thank you.

**Comment by Aadil101** [comment] 2022-09-30 21:15
The authors of CompLex provided 3 separate datasets: train, trial, and test. The "trial" dataset is the dev set!

**Comment by Dsakula** [comment] 2022-10-01 03:45
@Aadil101 Thank you very much! I also need to know the role of the "single_train_mini_idx. npy" and "single_dev_mini_idx. npy" files in ”discovery/pipeline_single.ipynb“. Because you did not provide them, I encountered obstacles in filtering features. I hope you can supplement these two documents. I would appreciate it if you could reply as soon as possible.

**Comment by Dsakula** [comment] 2022-10-01 03:47
@Aadil101 Thank you very much! I also need to know the role of the "single_train_mini_idx. npy" and "single_dev_mini_idx. npy" files in ”discovery/pipeline_single.ipynb“. Because I am not clear about the file function, I encountered an obstacle in the filtering function. I hope you can supplement these two documents. I would appreciate it if you could reply as soon as possible.

**Comment by Aadil101** [comment] 2022-10-01 06:59
Nice to hear you found the "discovery/pipeline_single.ipynb" notebook (for modeling lexical complexity of *single* words using a feature engineering-based approach). 

I subdivided the original CompLex train dataset into my own train_mini and dev_mini subsets (the suffix "_mini" is used to distinguish them from the train dataset they originate from). Note that I chose not to proceed with the CompLex train and trial datasets as my train and dev subsets (which would seem more intuitive to do) because I wanted to stratify my train and dev subsets across subcorpus and complexity score distributions (ie. ensuring a 'fair' split) before modeling. 

The files "single_train_mini_idx.npy" and "single_dev_mini_idx.npy" are numpy arrays storing the indices of the train dataset assigned to each subset (the prefix "single_" is just a reminder that in this notebook, we're handling data for the single word sub-task, not the multi-word sub-task (in the other notebook)). To reproduce these indices:

```{python}
single_train_mini_idx, single_dev_mini_idx = next(custom_cv_folds(single_train, n_splits=1, test_size=0.1))
np.save('{DIRECTORY}/single_train_mini_idx', single_train_mini_idx)
np.save('{DIRECTORY}/single_dev_mini_idx', single_dev_mini_idx)
```

If this is giving you trouble, you can omit stratifying and use the scikit-learn library's ```train_test_split``` function to split single_train. You can then save the row numbers in each subset into new variables single_train_mini_idx and single_dev_mini_idx.

**Closed as completed** 2022-11-03 22:38 UTC
